### ISSUE TITLE
Identical samples generated by nowcast_pipeline

### ISSUE THREAD

**Issue by akira-endo** [epiforecasts/EpiNow#29]
Identical samples are generated when argument sample>1 is given to nowcast_pipeline.
Lines 145-152 in nowcast_pipeline.R:
```
    sample_bin <- EpiNow::sample_onsets(
      onsets = case_counts_by_onset$cases,
      dates = case_counts_by_onset$date,
      cum_freq = delay_fn(1:nrow(case_counts_by_onset), dist = TRUE),
      report_delay = 0,
      samples = 1
    )[[1]] %>%
      dplyr::mutate(type = "nowcast", import_status = "local")
```
is suspicious

**Comment by seabbs** [comment]
Hmm that is odd. We aren’t using that at the moment though are we so
perhaps not a priority? A fix would be good.

Sam Abbott
Research Fellow - Real-time Modelling
London School of Hygiene and Tropical Medicine
Website: https:// <https://github.com/seabbs>samabbott.co.uk
Code: https://github.com/seabbs
Twitter: @seabbs


On 30 March 2020 at 14:46:54, akira-endo (notifications@github.com) wrote:

Identical samples are generated when argument sample>1 is given to
nowcast_pipeline.
Lines 145-152 in nowcast_pipeline.R:

    sample_bin <- EpiNow::sample_onsets(
      onsets = case_counts_by_onset$cases,
      dates = case_counts_by_onset$date,
      cum_freq = delay_fn(1:nrow(case_counts_by_onset), dist = TRUE),
      report_delay = 0,
      samples = 1
    )[[1]] %>%
      dplyr::mutate(type = "nowcast", import_status = "local")

is suspicious

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/epiforecasts/EpiNow/issues/29>, or unsubscribe

**Comment by akira-endo** [comment]
Just realised it was because of an error on my side!

**Comment by seabbs** [comment]
Phew!
