### ISSUE TITLE
Installation fails because "countrycode" is in Suggests, but should be in Imports

### ISSUE THREAD

**Issue by manulari** [epiforecasts/EpiNow#90]
Installation of EpiNow fails with

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  there is no package called ‘countrycode’
```

`countrycode` is listed in `Suggests`, but not in `Imports`.

installing with `devtools::install_github("epiforecasts/EpiNow",dependencies=TRUE) ` (which also installs `Suggests`) succeeds

**Comment by seabbs** [comment]
Thanks for flagging this should be fixed in master. To reduce dependencies we moved the mapping into a suggests (so `world_map`, `country_map` will require suggested packages) as not required by most users. Unfortunately, we missed out on updating the namespace which is now down. 

Please reopen if this doesn't fix.
